/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentSallesRouteImport } from './routes/student.salles'
import { Route as StudentReservationsRouteImport } from './routes/student.reservations'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentEquipmentRouteImport } from './routes/student.equipment'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as ProfessorSallesRouteImport } from './routes/professor.salles'
import { Route as ProfessorReservationsRouteImport } from './routes/professor.reservations'
import { Route as ProfessorProfileRouteImport } from './routes/professor.profile'
import { Route as ProfessorEquipmentRouteImport } from './routes/professor.equipment'
import { Route as ProfessorDashboardRouteImport } from './routes/professor.dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSallesRouteImport } from './routes/admin.salles'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminEquipmentRouteImport } from './routes/admin.equipment'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSallesRoute = StudentSallesRouteImport.update({
  id: '/salles',
  path: '/salles',
  getParentRoute: () => StudentRoute,
} as any)
const StudentReservationsRoute = StudentReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEquipmentRoute = StudentEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const ProfessorSallesRoute = ProfessorSallesRouteImport.update({
  id: '/salles',
  path: '/salles',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorReservationsRoute = ProfessorReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorProfileRoute = ProfessorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorEquipmentRoute = ProfessorEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorDashboardRoute = ProfessorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProfessorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSallesRoute = AdminSallesRouteImport.update({
  id: '/salles',
  path: '/salles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipmentRoute = AdminEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/professor': typeof ProfessorRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/salles': typeof AdminSallesRoute
  '/admin/users': typeof AdminUsersRoute
  '/professor/dashboard': typeof ProfessorDashboardRoute
  '/professor/equipment': typeof ProfessorEquipmentRoute
  '/professor/profile': typeof ProfessorProfileRoute
  '/professor/reservations': typeof ProfessorReservationsRoute
  '/professor/salles': typeof ProfessorSallesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/equipment': typeof StudentEquipmentRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/reservations': typeof StudentReservationsRoute
  '/student/salles': typeof StudentSallesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/professor': typeof ProfessorRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/salles': typeof AdminSallesRoute
  '/admin/users': typeof AdminUsersRoute
  '/professor/dashboard': typeof ProfessorDashboardRoute
  '/professor/equipment': typeof ProfessorEquipmentRoute
  '/professor/profile': typeof ProfessorProfileRoute
  '/professor/reservations': typeof ProfessorReservationsRoute
  '/professor/salles': typeof ProfessorSallesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/equipment': typeof StudentEquipmentRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/reservations': typeof StudentReservationsRoute
  '/student/salles': typeof StudentSallesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/professor': typeof ProfessorRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/equipment': typeof AdminEquipmentRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/salles': typeof AdminSallesRoute
  '/admin/users': typeof AdminUsersRoute
  '/professor/dashboard': typeof ProfessorDashboardRoute
  '/professor/equipment': typeof ProfessorEquipmentRoute
  '/professor/profile': typeof ProfessorProfileRoute
  '/professor/reservations': typeof ProfessorReservationsRoute
  '/professor/salles': typeof ProfessorSallesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/equipment': typeof StudentEquipmentRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/reservations': typeof StudentReservationsRoute
  '/student/salles': typeof StudentSallesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/professor'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/equipment'
    | '/admin/reservations'
    | '/admin/salles'
    | '/admin/users'
    | '/professor/dashboard'
    | '/professor/equipment'
    | '/professor/profile'
    | '/professor/reservations'
    | '/professor/salles'
    | '/student/dashboard'
    | '/student/equipment'
    | '/student/profile'
    | '/student/reservations'
    | '/student/salles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/professor'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/equipment'
    | '/admin/reservations'
    | '/admin/salles'
    | '/admin/users'
    | '/professor/dashboard'
    | '/professor/equipment'
    | '/professor/profile'
    | '/professor/reservations'
    | '/professor/salles'
    | '/student/dashboard'
    | '/student/equipment'
    | '/student/profile'
    | '/student/reservations'
    | '/student/salles'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/professor'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/equipment'
    | '/admin/reservations'
    | '/admin/salles'
    | '/admin/users'
    | '/professor/dashboard'
    | '/professor/equipment'
    | '/professor/profile'
    | '/professor/reservations'
    | '/professor/salles'
    | '/student/dashboard'
    | '/student/equipment'
    | '/student/profile'
    | '/student/reservations'
    | '/student/salles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfessorRoute: typeof ProfessorRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/salles': {
      id: '/student/salles'
      path: '/salles'
      fullPath: '/student/salles'
      preLoaderRoute: typeof StudentSallesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/reservations': {
      id: '/student/reservations'
      path: '/reservations'
      fullPath: '/student/reservations'
      preLoaderRoute: typeof StudentReservationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/equipment': {
      id: '/student/equipment'
      path: '/equipment'
      fullPath: '/student/equipment'
      preLoaderRoute: typeof StudentEquipmentRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/professor/salles': {
      id: '/professor/salles'
      path: '/salles'
      fullPath: '/professor/salles'
      preLoaderRoute: typeof ProfessorSallesRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/reservations': {
      id: '/professor/reservations'
      path: '/reservations'
      fullPath: '/professor/reservations'
      preLoaderRoute: typeof ProfessorReservationsRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/profile': {
      id: '/professor/profile'
      path: '/profile'
      fullPath: '/professor/profile'
      preLoaderRoute: typeof ProfessorProfileRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/equipment': {
      id: '/professor/equipment'
      path: '/equipment'
      fullPath: '/professor/equipment'
      preLoaderRoute: typeof ProfessorEquipmentRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/dashboard': {
      id: '/professor/dashboard'
      path: '/dashboard'
      fullPath: '/professor/dashboard'
      preLoaderRoute: typeof ProfessorDashboardRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salles': {
      id: '/admin/salles'
      path: '/salles'
      fullPath: '/admin/salles'
      preLoaderRoute: typeof AdminSallesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipment': {
      id: '/admin/equipment'
      path: '/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AdminEquipmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEquipmentRoute: typeof AdminEquipmentRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminSallesRoute: typeof AdminSallesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEquipmentRoute: AdminEquipmentRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminSallesRoute: AdminSallesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfessorRouteChildren {
  ProfessorDashboardRoute: typeof ProfessorDashboardRoute
  ProfessorEquipmentRoute: typeof ProfessorEquipmentRoute
  ProfessorProfileRoute: typeof ProfessorProfileRoute
  ProfessorReservationsRoute: typeof ProfessorReservationsRoute
  ProfessorSallesRoute: typeof ProfessorSallesRoute
}

const ProfessorRouteChildren: ProfessorRouteChildren = {
  ProfessorDashboardRoute: ProfessorDashboardRoute,
  ProfessorEquipmentRoute: ProfessorEquipmentRoute,
  ProfessorProfileRoute: ProfessorProfileRoute,
  ProfessorReservationsRoute: ProfessorReservationsRoute,
  ProfessorSallesRoute: ProfessorSallesRoute,
}

const ProfessorRouteWithChildren = ProfessorRoute._addFileChildren(
  ProfessorRouteChildren,
)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentEquipmentRoute: typeof StudentEquipmentRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentReservationsRoute: typeof StudentReservationsRoute
  StudentSallesRoute: typeof StudentSallesRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentEquipmentRoute: StudentEquipmentRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentReservationsRoute: StudentReservationsRoute,
  StudentSallesRoute: StudentSallesRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfessorRoute: ProfessorRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
